### PR TITLE
Golang and other dependencies upgrade

### PR DESCRIPTION
**Pull request by ravinitp**
# Overview:
Previously, the terraform-provider-template repository encountered challenges with **arm** build publication due to its reliance on Go version 1.11. In response, this pull request aims to address these issues by implementing several key changes.

Changes:

**Go Version Upgrade**: The Go version has been upgraded to go1.21.8, resolving compatibility issues and enabling successful arm build publication.
**Dependency Update**: Dependencies have been updated to utilize the [terraform-plugin-sdk](https://github.com/hashicorp/terraform-plugin-sdk/releases/tag/v2.33.0) instead of relying on terraform packages for schema and state file management. This enhancement ensures better integration and alignment with the Terraform ecosystem.
**Unit Test Fixes**: Unit tests have been fixed to accommodate the updated dependencies and ensure consistent functionality across different environments.
Impact:
These changes pave the way for smoother arm build publication and improve the overall reliability and compatibility of the terraform-provider-template repository. By upgrading dependencies and addressing compatibility issues, this pull request enhances the development experience for contributors and users alike.

# Testing:
The updated code has been rigorously tested to verify its compatibility.
Unit tests have been executed to validate the functionality of the changes and ensure that the terraform-provider-template repository maintains its high standards of quality.

Additional Notes:
Feedback and contributions from the community are welcome and encouraged. Please review the changes and provide any feedback or suggestions for further improvement. Thank you for your collaboration and support in advancing the terraform-provider-template project.

### CODE REVIEW

**Comment by ravinitp** [comment]
example log
```
variable "consul_addr" {
  default = "localhost:8000"
}

resource "template_dir" "config" {
  source_dir      = "${path.module}/instance_config_templates"
  destination_dir = "${path.cwd}/instance_config"

  vars = {
    consul_address = var.consul_addr
  }
}

# Render a part using a `template_file`
data "template_file" "script" {
  template = "${file("${path.module}/init.tpl")}"

  vars = {
    consul_address = var.consul_addr
  }
}

# Render a multi-part cloud-init config making use of the part
# above, and other source files
data "template_cloudinit_config" "config" {
  gzip          = true
  base64_encode = true

  # Main cloud-config configuration file.
  part {
    filename     = "init.cfg"
    content_type = "text/cloud-config"
    content      = "${data.template_file.script.rendered}"
  }

  part {
    content_type = "text/x-shellscript"
    content      = "baz"
  }

  part {
    content_type = "text/x-shellscript"
    content      = "ffbaz"
  }
}

output "template_file_rendered" {
  value = "${data.template_file.script.rendered}"
}

output "template_cloudinit_config" {
  value = "${data.template_cloudinit_config.config.rendered}"
}
```
- terraform init
- terraform apply
- terraform destroy
[tfptemplate.log](https://github.com/opentofu/terraform-provider-template/files/15105223/tfptemplate.log)

**Comment by ravinitp** [comment]
# Backward compatibility test
[TERRAFORM_PLAN_WITH_LOCAL_PROVIDER.log](https://github.com/opentofu/terraform-provider-template/files/15105291/TERRAFORM_PLAN_WITH_LOCAL_PROVIDER.log)
[TERRAFORM_APPLY_WITH_PUBLIC_PROVIDER.log](https://github.com/opentofu/terraform-provider-template/files/15105293/TERRAFORM_APPLY_WITH_PUBLIC_PROVIDER.log)

[TERRAFORM_DESTROY_WITH_LOCAL_PROVIDER.log](https://github.com/opentofu/terraform-provider-template/files/15105289/TERRAFORM_DESTROY_WITH_LOCAL_PROVIDER.log)

**Comment by ravinitp** [comment]
Unit/Integration test
```
ravbhart-mac:terraform-provider-template ravbhart$ make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?   	github.com/terraform-providers/terraform-provider-template	[no test files]
=== RUN   TestRender
--- PASS: TestRender (5.67s)
=== RUN   TestRender_handlePanic
--- PASS: TestRender_handlePanic (0.86s)
=== RUN   TestTemplateRendering
=== RUN   TestTemplateRendering/ABC_with_{}
    datasource_template_file_test.go:37: testing with this generated config:
        
        		data "template_file" "t0" {
        			template = "ABC"
        			vars = {}
        		}
        		output "rendered" {
        			value = "${data.template_file.t0.rendered}"
        		}
=== RUN   TestTemplateRendering/$${a}_with_{a="foo"}
    datasource_template_file_test.go:37: testing with this generated config:
        
        		data "template_file" "t0" {
        			template = "$${a}"
        			vars = {a="foo"}
        		}
        		output "rendered" {
        			value = "${data.template_file.t0.rendered}"
        		}
=== RUN   TestTemplateRendering/$${replace(a,_\"ello\",_\"i\")}_with_{a="hello"}
    datasource_template_file_test.go:37: testing with this generated config:
        
        		data "template_file" "t0" {
        			template = "$${replace(a, \"ello\", \"i\")}"
        			vars = {a="hello"}
        		}
        		output "rendered" {
        			value = "${data.template_file.t0.rendered}"
        		}
=== RUN   TestTemplateRendering/${1+2+3}_with_{}
    datasource_template_file_test.go:37: testing with this generated config:
        
        		data "template_file" "t0" {
        			template = "${1+2+3}"
        			vars = {}
        		}
        		output "rendered" {
        			value = "${data.template_file.t0.rendered}"
        		}
=== RUN   TestTemplateRendering//_with_{}
    datasource_template_file_test.go:37: testing with this generated config:
        
        		data "template_file" "t0" {
        			template = "/"
        			vars = {}
        		}
        		output "rendered" {
        			value = "${data.template_file.t0.rendered}"
        		}
=== RUN   TestTemplateRendering/%{_for_x_in_["a",_"b",_"c"]_}${x};%{_endfor_}_with_{}
    datasource_template_file_test.go:37: testing with this generated config:
        
        		data "template_file" "t0" {
        			template = "%{ for x in ["a", "b", "c"] }${x};%{ endfor }"
        			vars = {}
        		}
        		output "rendered" {
        			value = "${data.template_file.t0.rendered}"
        		}
--- PASS: TestTemplateRendering (9.82s)
    --- PASS: TestTemplateRendering/ABC_with_{} (2.11s)
    --- PASS: TestTemplateRendering/$${a}_with_{a="foo"} (1.50s)
    --- PASS: TestTemplateRendering/$${replace(a,_\"ello\",_\"i\")}_with_{a="hello"} (1.49s)
    --- PASS: TestTemplateRendering/${1+2+3}_with_{} (1.52s)
    --- PASS: TestTemplateRendering//_with_{} (1.67s)
    --- PASS: TestTemplateRendering/%{_for_x_in_["a",_"b",_"c"]_}${x};%{_endfor_}_with_{} (1.53s)
=== RUN   TestValidateVarsAttribute
--- PASS: TestValidateVarsAttribute (0.00s)
=== RUN   TestTemplateSharedMemoryRace
--- PASS: TestTemplateSharedMemoryRace (0.00s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestTemplateDirRendering
--- PASS: TestTemplateDirRendering (1.63s)
PASS
ok  	github.com/terraform-providers/terraform-provider-template/template	20.752s
```

**Comment by Yantrio** [comment]
Hi, we are not accepting pull requests into this repository as we discussed in this issue here: https://github.com/opentofu/registry/issues/395#issuecomment-2052134145

I would also like to refer you to a section on this in our contributing guide: https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#can-you-fix-a-bug-in-or-add-a-feature-to-the-hashicorp-providers-such-as-aws-azure-etc

I will be closing this PR, and we can continue discussion [here](https://github.com/opentofu/registry/issues/395) about how we can introduce a build process for linux/arm64.

**Pull request closed without merging**
